name: paladinsportal
description: A new Flutter project.
publish_to: "none"
version: 0.1.0+3

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  contactus: ^1.2.3
  crypto: ^3.0.3
  favorite_button: ^0.0.4
  flutter:
    sdk: flutter
  horizontal_data_table: ^4.2.0
  http: ^0.13.6
  intl: ^0.18.1
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/paladinsportalicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/talentos/
    - assets/campeones/
